### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by sandangel** [tmaiaroto/aegis#10]
Sorry if I missed anything but How to install this project. I 've search for go and npm package but there was no result. Do I have to clone and build this project to have a binary file for aegis CLI ?

**Comment by sandangel** [comment]
Oh I missed go get, sorry

**Comment by tmaiaroto** [comment]
No problem. I also need to put some releases up with pre-compiled binaries for various platforms. I hope to look into that sooner than later. I wanted to add some more features first, but since they are less common for me to use I haven't really added them yet.
