### ISSUE TITLE
build github.com/tmaiaroto/aegis: cannot find module for path github.com/kamilsk

### ISSUE THREAD

**Issue by davidsteed** [tmaiaroto/aegis#40]
I am getting this error when building

**Comment by tmaiaroto** [comment]
Do you have `GO111MODULE=on` environment variable set (or on CLI before your command)?

**Comment by davidsteed** [comment]
Yes it was on. I have manually worked round the problem. Kamilsk has made
changes (a mistake) so you can no longer use modules to get v3 of his
library. I manually pulled it had to edit a couple of file’s import paths
and built it. V4 of his library has deprecated some functions that you use.
May be worth looking at v4 or getting him to back out the change he has
made.

**Comment by tmaiaroto** [comment]
Thanks! I appreciate you tracking that down for me. I'll update to v4.
