### ISSUE TITLE
aegis deploy error

### ISSUE THREAD

**Issue by joshglazer** [tmaiaroto/aegis#41]
I created a blank project using `aegis init` but am getting an error when trying to deploy.

`$ aegis deploy`
`There was a problem building the Go app for the Lambda function.`
`exit status 1`

Is there anything I should change in order to deploy this project?

**Comment by tmaiaroto** [comment]
I'll take a look to see if there's been any sort of updates to dependencies that caused a problem. I've also been thinking about vendoring them. 

Which go version are you using?

**Comment by joshglazer** [comment]
Here's my version number:

```
$ go version
go version go1.12.4 darwin/amd64
```

I'm still very new to go, so I wanted to make sure I am doing this correctly.  Here are the steps I took:

```
cd $GOPATH/src/github.com/joshglazer
mkdir aegis-demo
cd aegis-demo
aegis init
go get .
aegis deploy
```

I already have the aws-cli set up with `~/.aws/credentials` and `~/.aws/config` files

I didn't make any changes to any of the initialized files, I just wanted to see it in action first before changing the endpoint.  Are there any other steps or code changes that I have to make?

**Comment by tmaiaroto** [comment]
I don't think so. You might need to ensure you have go modules enabled. `GO111MODULE=on` but I'll double check. Also, give `go get` command a try. See if there's any errors building.

**Comment by joshglazer** [comment]
Thanks for all of the help.  I'm still having issues though.

When I turn that setting on by running: 

`export GO111MODULE=on`

I get the following error when running the `go get .` command:

`go: cannot find main module; see 'go help modules'`

Is this the correct way to turn that setting on? Or is there something else that I'm missing?

**Comment by joshglazer** [comment]
Hey, thanks again for the help earlier.  I was about to get everything working by turning on that setting (`export GO111MODULE=on`) and then running the following commands:

```
go mod init
go test
```

I'm looking forward to using the framework, and hopefully this thread can help other people that have issues getting it set up.

Thanks again!
