### ISSUE TITLE
How could one change the default 3 second timeout for (Basic Settings)

### ISSUE THREAD

**Issue by gilgameshskytrooper** [tmaiaroto/aegis#43]
I see in one of the examples that you can set an `api->resourceTimeoutMs`, but this doesn't seem to change the Basic Setting timeout in Lambda:

![img](https://66.media.tumblr.com/5e30b2c2e02655c431d54264f99c0909/tumblr_ps6re9nwoP1xbkxdso1_540.png)

Please let me know if there is a setting to change this.

Thank you

**Comment by gilgameshskytrooper** [comment]
Also, is there like a `destroy` command which would let you take down everything aegis created?

**Comment by tmaiaroto** [comment]
It should just be the `timeout` key value under the `lambda` section of the YAML. Anything that goes on about "api" would be related to AWS API Gateway if your app was using it. You can take a look at the files in the `cmd` directory of this repo to see what it parses from YAML. I'll double check documentation and add a task to enhance it if I forgot to include a section about the YAML config or if it wasn't deep enough.

**Comment by tmaiaroto** [comment]
Also, there is no destroy command. Aegis wasn't originally designed to be a robust infrastructure management solution. It was more around writing serverless functions/apps/services. The deploy commands are mainly considered development convenience. The default role created, for example, is somewhat permissive in order for all of the various integrations and Lambda triggers to work with ease.

I typically reach for something like Terraform for production infrastructure management solutions, leaving Aegis' CLI just for development. Well, unless it's just me or a small project, then I may not bother with Terraform either.

**Comment by gilgameshskytrooper** [comment]
I see. thanks a bunch.
