### ISSUE TITLE
There was a problem building the Go app for the Lambda function.

### ISSUE THREAD

**Issue by varung** [tmaiaroto/aegis#44]
I ran:

> aegis init
> aegis deploy
There was a problem building the Go app for the Lambda function.
exit status 1

Is there something I'm supposed to do after init?

**Comment by tmaiaroto** [comment]
I see, it's because go modules. I'll have a fix soon (as well as some more detailed output for the CLI tool).

**Comment by tmaiaroto** [comment]
Basically removing this line here: https://github.com/tmaiaroto/aegis/blob/master/cmd/deploy.go#L200
should fix the issue. Though what I'm also adding is the ability to set (and override) environment variables from the `aegis.yaml` config.

I'm also adding some more output for AWS error responses.

**Comment by tmaiaroto** [comment]
You may be able to ensure your app uses go modules and then deploy without issues. The example/boilerplate from init command doesn't.

**Comment by tmaiaroto** [comment]
Release 1.16.3 should resolve this issue and make for better developer experience with additional CLI output. https://github.com/tmaiaroto/aegis/releases/tag/1.16.3
